apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-charts.fullname" . }}
  labels: 
    {{- include "helm-charts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-charts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.containerName }}
          image: {{ required "Pass valid docker image name" .Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-charts.fullname" . }}
  labels:
    {{- include "helm-charts.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: port8080
      nodePort: {{ .Values.nodePort }}
  selector: 
    {{- include "helm-charts.selectorLabels" . | nindent 4 }}