apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.name }}
  labels: 
    app: {{ .Chart.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.name }}
    spec:
      containers:
        - name: {{ .Values.containerName }}
          image: {{ required "Pass valid docker image name" .Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.name }}-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: port8080
      nodePort: {{ .Values.nodePort }}
  selector: 
    app: {{ .Chart.name }}